// Item IDs from Cairo contract
export const ItemId = {
    Pendant: 1,
    Necklace: 2,
    Amulet: 3,
    SilverRing: 4,
    BronzeRing: 5,
    PlatinumRing: 6,
    TitaniumRing: 7,
    GoldRing: 8,
    GhostWand: 9,
    GraveWand: 10,
    BoneWand: 11,
    Wand: 12,
    Grimoire: 13,
    Chronicle: 14,
    Tome: 15,
    Book: 16,
    DivineRobe: 17,
    SilkRobe: 18,
    LinenRobe: 19,
    Robe: 20,
    Shirt: 21,
    Crown: 22,
    DivineHood: 23,
    SilkHood: 24,
    LinenHood: 25,
    Hood: 26,
    BrightsilkSash: 27,
    SilkSash: 28,
    WoolSash: 29,
    LinenSash: 30,
    Sash: 31,
    DivineSlippers: 32,
    SilkSlippers: 33,
    WoolShoes: 34,
    LinenShoes: 35,
    Shoes: 36,
    DivineGloves: 37,
    SilkGloves: 38,
    WoolGloves: 39,
    LinenGloves: 40,
    Gloves: 41,
    Katana: 42,
    Falchion: 43,
    Scimitar: 44,
    LongSword: 45,
    ShortSword: 46,
    DemonHusk: 47,
    DragonskinArmor: 48,
    StuddedLeatherArmor: 49,
    HardLeatherArmor: 50,
    LeatherArmor: 51,
    DemonCrown: 52,
    DragonsCrown: 53,
    WarCap: 54,
    LeatherCap: 55,
    Cap: 56,
    DemonhideBelt: 57,
    DragonskinBelt: 58,
    StuddedLeatherBelt: 59,
    HardLeatherBelt: 60,
    LeatherBelt: 61,
    DemonhideBoots: 62,
    DragonskinBoots: 63,
    StuddedLeatherBoots: 64,
    HardLeatherBoots: 65,
    LeatherBoots: 66,
    DemonsHands: 67,
    DragonskinGloves: 68,
    StuddedLeatherGloves: 69,
    HardLeatherGloves: 70,
    LeatherGloves: 71,
    Warhammer: 72,
    Quarterstaff: 73,
    Maul: 74,
    Mace: 75,
    Club: 76,
    HolyChestplate: 77,
    OrnateChestplate: 78,
    PlateMail: 79,
    ChainMail: 80,
    RingMail: 81,
    AncientHelm: 82,
    OrnateHelm: 83,
    GreatHelm: 84,
    FullHelm: 85,
    Helm: 86,
    OrnateBelt: 87,
    WarBelt: 88,
    PlatedBelt: 89,
    MeshBelt: 90,
    HeavyBelt: 91,
    HolyGreaves: 92,
    OrnateGreaves: 93,
    Greaves: 94,
    ChainBoots: 95,
    HeavyBoots: 96,
    HolyGauntlets: 97,
    OrnateGauntlets: 98,
    Gauntlets: 99,
    ChainGloves: 100,
    HeavyGloves: 101
} as const;

// Item Slot Length
export const ItemSlotLength = {
    SlotItemsLengthWeapon: 18,
    SlotItemsLengthChest: 15,
    SlotItemsLengthHead: 15,
    SlotItemsLengthWaist: 15,
    SlotItemsLengthFoot: 15,
    SlotItemsLengthHand: 15,
    SlotItemsLengthNeck: 3,
    SlotItemsLengthRing: 5
} as const;

// Item Index
export const ItemIndex = {
    // Weapon
    Warhammer: 0,
    Quarterstaff: 1,
    Maul: 2,
    Mace: 3,
    Club: 4,
    Katana: 5,
    Falchion: 6,
    Scimitar: 7,
    LongSword: 8,
    ShortSword: 9,
    GhostWand: 10,
    GraveWand: 11,
    BoneWand: 12,
    Wand: 13,
    Grimoire: 14,
    Chronicle: 15,
    Tome: 16,
    Book: 17,

    // Chest
    DivineRobe: 0,
    SilkRobe: 1,
    LinenRobe: 2,
    Robe: 3,
    Shirt: 4,
    DemonHusk: 5,
    DragonskinArmor: 6,
    StuddedLeatherArmor: 7,
    HardLeatherArmor: 8,
    LeatherArmor: 9,
    HolyChestplate: 10,
    OrnateChestplate: 11,
    PlateMail: 12,
    ChainMail: 13,
    RingMail: 14,

    // Head
    AncientHelm: 0,
    OrnateHelm: 1,
    GreatHelm: 2,
    FullHelm: 3,
    Helm: 4,
    DemonCrown: 5,
    DragonsCrown: 6,
    WarCap: 7,
    LeatherCap: 8,
    Cap: 9,
    Crown: 10,
    DivineHood: 11,
    SilkHood: 12,
    LinenHood: 13,
    Hood: 14,

    // Waist
    OrnateBelt: 0,
    WarBelt: 1,
    PlatedBelt: 2,
    MeshBelt: 3,
    HeavyBelt: 4,
    DemonhideBelt: 5,
    DragonskinBelt: 6,
    StuddedLeatherBelt: 7,
    HardLeatherBelt: 8,
    LeatherBelt: 9,
    BrightsilkSash: 10,
    SilkSash: 11,
    WoolSash: 12,
    LinenSash: 13,
    Sash: 14,

    // Foot
    HolyGreaves: 0,
    OrnateGreaves: 1,
    Greaves: 2,
    ChainBoots: 3,
    HeavyBoots: 4,
    DemonhideBoots: 5,
    DragonskinBoots: 6,
    StuddedLeatherBoots: 7,
    HardLeatherBoots: 8,
    LeatherBoots: 9,
    DivineSlippers: 10,
    SilkSlippers: 11,
    WoolShoes: 12,
    LinenShoes: 13,
    Shoes: 14,

    // Hand
    HolyGauntlets: 0,
    OrnateGauntlets: 1,
    Gauntlets: 2,
    ChainGloves: 3,
    HeavyGloves: 4,
    DemonsHands: 5,
    DragonskinGloves: 6,
    StuddedLeatherGloves: 7,
    HardLeatherGloves: 8,
    LeatherGloves: 9,
    DivineGloves: 10,
    SilkGloves: 11,
    WoolGloves: 12,
    LinenGloves: 13,
    Gloves: 14,

    // Necklaces
    Necklace: 0,
    Amulet: 1,
    Pendant: 2,

    // Rings
    GoldRing: 0,
    SilverRing: 1,
    BronzeRing: 2,
    PlatinumRing: 3,
    TitaniumRing: 4
} as const;

// Item Name Prefixes
export const ItemNamePrefix = {
    Agony: 1,
    Apocalypse: 2,
    Armageddon: 3,
    Beast: 4,
    Behemoth: 5,
    Blight: 6,
    Blood: 7,
    Bramble: 8,
    Brimstone: 9,
    Brood: 10,
    Carrion: 11,
    Cataclysm: 12,
    Chimeric: 13,
    Corpse: 14,
    Corruption: 15,
    Damnation: 16,
    Death: 17,
    Demon: 18,
    Dire: 19,
    Dragon: 20,
    Dread: 21,
    Doom: 22,
    Dusk: 23,
    Eagle: 24,
    Empyrean: 25,
    Fate: 26,
    Foe: 27,
    Gale: 28,
    Ghoul: 29,
    Gloom: 30,
    Glyph: 31,
    Golem: 32,
    Grim: 33,
    Hate: 34,
    Havoc: 35,
    Honour: 36,
    Horror: 37,
    Hypnotic: 38,
    Kraken: 39,
    Loath: 40,
    Maelstrom: 41,
    Mind: 42,
    Miracle: 43,
    Morbid: 44,
    Oblivion: 45,
    Onslaught: 46,
    Pain: 47,
    Pandemonium: 48,
    Phoenix: 49,
    Plague: 50,
    Rage: 51,
    Rapture: 52,
    Rune: 53,
    Skull: 54,
    Sol: 55,
    Soul: 56,
    Sorrow: 57,
    Spirit: 58,
    Storm: 59,
    Tempest: 60,
    Torment: 61,
    Vengeance: 62,
    Victory: 63,
    Viper: 64,
    Vortex: 65,
    Woe: 66,
    Wrath: 67,
    Lights: 68,
    Shimmering: 69
} as const;

// Item Name Suffixes
export const ItemNameSuffix = {
    Bane: 1,
    Root: 2,
    Bite: 3,
    Song: 4,
    Roar: 5,
    Grasp: 6,
    Instrument: 7,
    Glow: 8,
    Bender: 9,
    Shadow: 10,
    Whisper: 11,
    Shout: 12,
    Growl: 13,
    Tear: 14,
    Peak: 15,
    Form: 16,
    Sun: 17,
    Moon: 18
} as const;

// Item Suffixes
export const ItemSuffix = {
    of_Power: 1,
    of_Giant: 2,
    of_Titans: 3,
    of_Skill: 4,
    of_Perfection: 5,
    of_Brilliance: 6,
    of_Enlightenment: 7,
    of_Protection: 8,
    of_Anger: 9,
    of_Rage: 10,
    of_Fury: 11,
    of_Vitriol: 12,
    of_the_Fox: 13,
    of_Detection: 14,
    of_Reflection: 15,
    of_the_Twins: 16
} as const;

// Constants
export const NUM_ITEMS = 101;
export const NamePrefixLength = 69;
export const NameSuffixLength = 18;
export const ItemSuffixLength = 16;
export const SUFFIX_UNLOCK_GREATNESS = 15;
export const PREFIXES_UNLOCK_GREATNESS = 19;

export const ITEM_NAME_PREFIXES: { [key: number]: string } = {
    1: "Agony", 2: "Apocalypse", 3: "Armageddon", 4: "Beast", 5: "Behemoth",
    6: "Blight", 7: "Blood", 8: "Bramble", 9: "Brimstone", 10: "Brood",
    11: "Carrion", 12: "Cataclysm", 13: "Chimeric", 14: "Corpse", 15: "Corruption",
    16: "Damnation", 17: "Death", 18: "Demon", 19: "Dire", 20: "Dragon",
    21: "Dread", 22: "Doom", 23: "Dusk", 24: "Eagle", 25: "Empyrean",
    26: "Fate", 27: "Foe", 28: "Gale", 29: "Ghoul", 30: "Gloom",
    31: "Glyph", 32: "Golem", 33: "Grim", 34: "Hate", 35: "Havoc",
    36: "Honour", 37: "Horror", 38: "Hypnotic", 39: "Kraken", 40: "Loath",
    41: "Maelstrom", 42: "Mind", 43: "Miracle", 44: "Morbid", 45: "Oblivion",
    46: "Onslaught", 47: "Pain", 48: "Pandemonium", 49: "Phoenix", 50: "Plague",
    51: "Rage", 52: "Rapture", 53: "Rune", 54: "Skull", 55: "Sol",
    56: "Soul", 57: "Sorrow", 58: "Spirit", 59: "Storm", 60: "Tempest",
    61: "Torment", 62: "Vengeance", 63: "Victory", 64: "Viper", 65: "Vortex",
    66: "Woe", 67: "Wrath", 68: "Lights", 69: "Shimmering"
};

export const ITEM_NAME_SUFFIXES: { [key: number]: string } = {
    1: "Bane", 2: "Root", 3: "Bite", 4: "Song", 5: "Roar",
    6: "Grasp", 7: "Instrument", 8: "Glow", 9: "Bender", 10: "Shadow",
    11: "Whisper", 12: "Shout", 13: "Growl", 14: "Tear", 15: "Peak",
    16: "Form", 17: "Sun", 18: "Moon"
};

export const ITEM_SUFFIXES: { [key: number]: string } = {
    1: "of Power", 2: "of Giant", 3: "of Titans", 4: "of Skill", 5: "of Perfection",
    6: "of Brilliance", 7: "of Enlightenment", 8: "of Protection", 9: "of Anger",
    10: "of Rage", 11: "of Fury", 12: "of Vitriol", 13: "of the Fox",
    14: "of Detection", 15: "of Reflection", 16: "of the Twins"
};