export const OBSTACLE_NAMES: { [key: number]: string } = {
  // Magical Obstacles
  1: "Demonic Altar",
  2: "Vortex of Despair",
  3: "Eldritch Barrier",
  4: "Soul Trap",
  5: "Phantom Vortex",
  6: "Ectoplasmic Web",
  7: "Spectral Chains",
  8: "Infernal Pact",
  9: "Arcane Explosion",
  10: "Hypnotic Essence",
  11: "Mischievous Sprites",
  12: "Soul Draining Statue",
  13: "Petrifying Gaze",
  14: "Summoning Circle",
  15: "Ethereal Void",
  16: "Magic Lock",
  17: "Bewitching Fog",
  18: "Illusionary Maze",
  19: "Spellbound Mirror",
  20: "Ensnaring Shadow",
  21: "Dark Mist",
  22: "Curse",
  23: "Haunting Echo",
  24: "Hex",
  25: "Ghostly Whispers",

  // Sharp Obstacles
  26: "Pendulum Blades",
  27: "Icy Razor Winds",
  28: "Acidic Thorns",
  29: "Dragon's Breath",
  30: "Pendulum Scythe",
  31: "Flame Jet",
  32: "Piercing Ice Darts",
  33: "Glass Sand Storm",
  34: "Poisoned Dart Wall",
  35: "Spinning Blade Wheel",
  36: "Poison Dart",
  37: "Spiked Tumbleweed",
  38: "Thunderbolt",
  39: "Giant Bear Trap",
  40: "Steel Needle Rain",
  41: "Spiked Pit",
  42: "Diamond Dust Storm",
  43: "Trapdoor Scorpion Pit",
  44: "Bladed Fan",
  45: "Bear Trap",
  46: "Porcupine Quill",
  47: "Hidden Arrow",
  48: "Glass Shard",
  49: "Thorn Bush",
  50: "Jagged Rocks",

  // Crushing Obstacles
  51: "Collapsing Ceiling",
  52: "Rockslide",
  53: "Flash Flood",
  54: "Clinging Roots",
  55: "Collapsing Cavern",
  56: "Crushing Walls",
  57: "Smashing Pillars",
  58: "Rumbling Catacomb",
  59: "Whirling Cyclone",
  60: "Erupting Earth",
  61: "Subterranean Tremor",
  62: "Falling Chandelier",
  63: "Collapsing Bridge",
  64: "Raging Sandstorm",
  65: "Avalanching Rocks",
  66: "Tumbling Boulders",
  67: "Slamming Iron Gate",
  68: "Shifting Sandtrap",
  69: "Erupting Mud Geyser",
  70: "Crumbling Staircase",
  71: "Swinging Logs",
  72: "Unstable Cliff",
  73: "Toppling Statue",
  74: "Tumbling Barrels",
  75: "Rolling Boulder"
}; 